# version: "3.8"

services:
  api:
    build: .
    container_name: "ai_stylist_api"
    image: "docker.io/ai_stylist_api"
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - ai-stylist-network
    depends_on:
      - db
    restart: "always"

  db:
    image: redis:latest
    container_name: "ai_stylist_db"
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    ports:
      - "6379:6379"
    networks:
      - ai-stylist-network
    volumes:
      - redis-data:/data
    restart: "always"

volumes:
  redis-data:
    driver: local

networks:
  ai-stylist-network:
    driver: bridge
