# version: "3.8"

services:
  api:
    build: .
    container_name: "ai_stylist_api"
    image: "docker.io/ai_stylist_api"
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - ai-stylist-network
    depends_on:
      - db
    restart: "always"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  db:
    image: redis:latest
    container_name: "ai_stylist_db"
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    ports:
      - "6379:6379"
    networks:
      - ai-stylist-network
    volumes:
      - redis-data:/data
    restart: "always"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  redis-data:
    driver: local

networks:
  ai-stylist-network:
    driver: bridge
